// This enum was generated by Dialoguer
//	Do not modify this file, it will be overwritten by Dialoguer.
public enum DialoguerDialogues{
	BoozyTest = 0,
	BoozyIntro = 1,
	Testing = 2,
	FurmProblem = 3,
	MaskCollision = 4,
	GamePlan = 5,
	QMDialogue = 6,
	EagleEliDialogue = 7,
	EagleEliAfterFight = 8,
	UwULewdFoxDialogue = 9,
	UwUAfterFight = 10,
	AwooConvo = 11,
}
